defaults:
  rng_seed: 42
  cache_dir: /pfss/laion/huggingface/datasets
  use_system_prefix: false
  datasets_extra: [] # For config options to add additional datasets, since yaml doesn't let us extend arrays
  eval_size:
  tokenizer_type:
  vocab_extra_ids_list: "<|im_start|>,<|im_end|>"
  dataset_impl: "mmap"
  min_assistant_tokens: 10
  output_dir_suffix: ""

llama2_de:
  vocab_file: "/pfss/laion/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9/tokenizer.model"
  tokenizer_type: "SentencePieceTokenizer"
  output_dir_suffix: "_llama2"

oasst_de:
  datasets:
    - oasst_de
  output_dir: "output/oasst_de"
  filename_prefix: "oasst_de"

evol_instruct_de:
  datasets:
    - sharegpt:
        hf_name: "FreedomIntelligence/evol-instruct-deutsch"
  output_dir: "output/evol_instruct_de"
  filename_prefix: "evol_instruct_de"

alpaca_gpt4_de:
  datasets:
    - sharegpt:
        hf_name: "FreedomIntelligence/alpaca-gpt4-deutsch"
  output_dir: "output/alpaca_gpt4_de"
  filename_prefix: "alpaca_gpt4_de"

openplatypus_de:
  datasets:
    - openplatypus:
        hf_name: "LeoLM/OpenSchnabeltier"
  output_dir: "output/openplatypus_de"
  filename_prefix: "openplatypus_de"

german_combined:
  datasets:
    - oasst_de:
        hf_name: "bjoernp/high_quality_oasst_de"
    - sharegpt:
        hf_name: "FreedomIntelligence/evol-instruct-deutsch"
    - sharegpt:
        hf_name: "FreedomIntelligence/alpaca-gpt4-deutsch"
    - openplatypus:
        hf_name: "LeoLM/OpenSchnabeltier"
  filename_prefix: "german_all"      

german_combinedv2:
  datasets:
    - oasst_de:
        hf_name: "bjoernp/high_quality_oasst_de"
        val_split: 0.05
    - sharegpt:
        hf_name: "FreedomIntelligence/evol-instruct-deutsch"
        val_split: 0.02
    - sharegpt:
        hf_name: "FreedomIntelligence/alpaca-gpt4-deutsch"
        val_split: 0.02
    - openplatypus:
        hf_name: "LeoLM/OpenSchnabeltier"
        val_split: 0.02
    - oasst_de:
        hf_name: "bjoernp/german_songs_conversation"
        val_split: 0.02
    - openplatypus:
        hf_name: "bjoernp/german_poems_gpt4"
        instruct_column: "prompt"
        output_column: "poem"
        val_split: 0.02
  filename_prefix: "german_combinedv2"      

german_pre_1:
  datasets:
    - openplatypus:
        hf_name: "LeoLM/OpenSchnabeltier"
    - beluga_chat
    - sharegpt:
        hf_name: "FreedomIntelligence/evol-instruct-deutsch"
    - sharegpt:
        hf_name: "FreedomIntelligence/alpaca-gpt4-deutsch"
    - oasst_de:
        hf_name: "bjoernp/german_songs_conversation"
    - openplatypus:
        hf_name: "bjoernp/poem_analyses"
        instruct_column: "prompt"
        output_column: "response"
    - openplatypus:
        hf_name: "bjoernp/german_poems_gpt4"
        instruct_column: "prompt"
        output_column: "poem"
  filename_prefix: "german_pre_1"

german_pre_2:
  datasets:
    - oasst_de:
        hf_name: "bjoernp/high_quality_oasst_de"
  filename_prefix: "german_pre_2"

bilingual_combined:
  datasets:
    - openplatypus:
        hf_name: "LeoLM/OpenSchnabeltier"
        val_split: 0.02
    - openplatypus:
        hf_name: "garage-bAInd/Open-Platypus"
        instruct_column: "instruction"
        output_column: "output"
        val_split: 0.02
    # - beluga_chat
    # - beluga_chat:
    #     hf_name: "CarperAI/orca-gpt4-100k-cleaned"
    #     system_column: "system"
    #     prompt_column: "prompt"
    #     response_column: "response"
    - openplatypus:
        hf_name: "WizardLM/WizardLM_evol_instruct_70k"
        instruct_column: "instruction"
        output_column: "output"
        val_split: 0.02
    - sharegpt:
        hf_name: "FreedomIntelligence/evol-instruct-deutsch"
        val_split: 0.02
    - sharegpt:
        hf_name: "FreedomIntelligence/alpaca-gpt4-deutsch"
        val_split: 0.02
    - oasst_de:
        hf_name: "bjoernp/german_songs_conversation"
        val_split: 0.02
    - openplatypus:
        hf_name: "bjoernp/poem_analyses"
        instruct_column: "prompt"
        output_column: "response"
        val_split: 0.02
    - openplatypus:
        hf_name: "bjoernp/german_poems_gpt4"
        instruct_column: "prompt"
        output_column: "poem"
        val_split: 0.02
    - oasst_de:
        hf_name: "bjoernp/high_quality_oasst_de"
        val_split: 0.02
    - oasst_de:
        hf_name: "bjoernp/oasst25-08-23-filtered"
        val_split: 0.02
  filename_prefix: "bilingual_pre_1"

bilingual_pre_2:
  datasets:
    - oasst_de:
        hf_name: "bjoernp/high_quality_oasst_de"
    - oasst_de:
        hf_name: "bjoernp/oasst25-08-23-filtered"
  filename_prefix: "bilingual_pre_2"